### ISSUE TITLE
Cannot start the application because Asciidoctor can't be loaded

### ISSUE THREAD

**Issue by rmpestano** [htmfilho/digger#14]
Hi,

I've tried to run Digger via `java -jar` but am getting the following error at app startup:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [digger.web.utils.Asciidoc]: Constructor threw exception; nested exception is java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1295) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	... 38 common frames omitted
Caused by: java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_222]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_222]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_222]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_222]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_222]
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:485) ~[asciidoctorj-api-2.1.0.jar!/:na]
	at digger.web.utils.Asciidoc.<init>(Asciidoc.java:17) ~[classes!/:0.5.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_222]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_222]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_222]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_222]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	... 40 common frames omitted
Caused by: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:987) ~[jruby-core-9.2.7.0.jar!/:na]
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54) ~[na:na]
	at RUBY.<main>(<script>:12) ~[na:na]
```

Any ideas?

Following is my local env:

```
rmpestano@oss-powerhouse:~/projects/digger$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
rmpestano@oss-powerhouse:~/projects/digger$ mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-60-generic", arch: "amd64", family: "unix"
rmpestano@oss-powerhouse:~/projects/digger$ asciidoctor -v
Asciidoctor 1.5.8 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

```
here's [full output](https://gist.githubusercontent.com/rmpestano/64b68b6a819dbeebe9ca13ff8d317940/raw/c20ca5a654e4862a9d59f0e1af2ce881454952b1/digger%2520output)

**Comment by rmpestano** [comment]
Running via `mvn spring-boot:run` does work.

**Comment by htmfilho** [comment]
Thanks for the feedback. Looking into it right now.

**Comment by htmfilho** [comment]
AsciidoctorJ depends on JRuby. SpringBoot uses a custom packaging system that doesn't work well with JRuby. Exploring `repackage` of the SpringBoot Maven Plugin to solve the issue.

**Comment by htmfilho** [comment]
Hi @rmpestano , 

please try again with this bug fix release: https://github.com/htmfilho/digger/releases/tag/0.5.1

**Comment by rmpestano** [comment]
Hi @htmfilho,

it is working now, thank you!
